export const CHANGE_SETTINGS_OPERAND = 'CHANGE_SETTINGS_OPERAND';
export const CHANGE_SETTINGS_OPERATION = 'CHANGE_SETTINGS_OPERATION';
export const CHANGE_SETTINGS_SPEED = 'CHANGE_SETTINGS_SPEED';
export const GENERATE_PROBLEM = 'GENERATE_PROBLEM';
export const DISPATCH_PROBLEM = 'DISPATCH_PROBLEM';
export const SEND_ANSWER = 'SEND_ANSWER';